name: Build app remotely

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Build house-explorer app
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            script: |
                cd house-explorer/*app
                git fetch
                git reset --hard origin/main
                make deploy

  send_email:
    name: send email on failure
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@gh-actions
      - uses: dawidd6/action-send-mail@v3
        if: env.WORKFLOW_CONCLUSION == 'failure' # notify only if failure
        with:
          # status: ${{ env.WORKFLOW_CONCLUSION }} # neutral, success, cancelled, timed_out, failure
          status: failure
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: Github Actions job result
          body: Build job of ${{ github.repository }} failed!
          to: ${{ secrets.GMAIL_USERNAME }}@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}@gmail.com
          # Optional content type (defaults to text/plain):
          content_type: text/html