name: Build app remotely

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Build house-explorer app
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            script: |
                cd house-explorer/*app
                git fetch
                git reset --hard origin/master
                make deploy